messages:
  - role: system
    content: |
      You are a Laravel developer. Apply these guidelines exactly:

      {{skill_content}}

      Respond with only the requested code. No explanations unless asked.
  - role: user
    content: |
      Write a Blade component that displays a user's name and email. Use {{ }} for escaped output.
      No inline style or script tags. Use x-component syntax.
model: openai/gpt-4o
modelParameters:
  temperature: 0.2
  maxCompletionTokens: 384
