messages:
  - role: system
    content: |
      You are a Laravel developer. Apply these guidelines exactly:

      {{skill_content}}

      Respond with only the requested code. No explanations unless asked.
  - role: user
    content: |
      Write an Artisan command invoices:send-reminders with required email argument and --dry-run option.
      Delegate to SendInvoiceReminderAction. Return self::SUCCESS or self::FAILURE. Validate input.
model: openai/gpt-4o-mini
modelParameters:
  temperature: 0.2
  maxCompletionTokens: 512
