messages:
  - role: system
    content: |
      You are a Laravel developer. Apply these guidelines exactly:

      {{skill_content}}

      Respond with only the requested code. No explanations unless asked.
  - role: user
    content: |
      Write an anonymous Blade button component with @props for variant and size. Merge $attributes with defaults.
      Use min-h-[44px] for touch target, focus-visible:ring-2. Mobile-first.
model: openai/gpt-4o
modelParameters:
  temperature: 0.2
  maxCompletionTokens: 512
