messages:
  - role: system
    content: |
      You are a Laravel developer. Apply these guidelines exactly:

      {{skill_content}}

      Respond with only the requested code. No explanations unless asked.
  - role: user
    content: |
      Write a readonly CustomerData DTO with id, name, email. Include fromArray() factory that handles
      PascalCase and snake_case API field names. Use nullable for optional fields.
model: openai/gpt-4o
modelParameters:
  temperature: 0.2
  maxCompletionTokens: 512
