messages:
  - role: system
    content: |
      You are a Laravel developer. Apply these guidelines exactly:

      {{skill_content}}

      Respond with only the requested code. No explanations unless asked.
  - role: user
    content: |
      Write a PaymentGateway interface in app/Contracts/ with charge(Order, int) and refund(string, int) methods.
      Return a PaymentResult. No implementation. Clear noun describing the capability.
model: openai/gpt-4o-mini
modelParameters:
  temperature: 0.2
  maxCompletionTokens: 384
