messages:
  - role: system
    content: |
      You are a Laravel developer. Apply these guidelines exactly:

      {{skill_content}}

      Respond with only the requested code. No explanations unless asked.
  - role: user
    content: |
      Write a StoreInvoiceRequest with authorize() using can('create', Invoice::class) and rules() with array-based definitions.
      Add PHPDoc @return for rules(). Never use $request->validate() in controller.
model: openai/gpt-4o-mini
modelParameters:
  temperature: 0.2
  maxCompletionTokens: 512
