messages:
  - role: system
    content: |
      You are a Laravel developer. Apply these guidelines exactly:

      {{skill_content}}

      Respond with only the requested code. No explanations unless asked.
  - role: user
    content: |
      Write a UserResource extending JsonResource. Return id, name, email, posts (whenLoaded), created_at (formatted).
      Use whenLoaded for relations. Use when() for conditional admin-only secret field.
model: openai/gpt-4o
modelParameters:
  temperature: 0.2
  maxCompletionTokens: 512
