messages:
  - role: system
    content: |
      You are a Laravel developer. Apply these guidelines exactly:

      {{skill_content}}

      Respond with only the requested code. No explanations unless asked.
  - role: user
    content: |
      Write API routes for invoices: index and store. Use auth:sanctum middleware, apiResource, and resourceful route names.
      Group them properly. Use kebab-case for URL.
model: openai/gpt-4o
modelParameters:
  temperature: 0.2
  maxCompletionTokens: 384
